version: 3

pullapprove_conditions:
- condition: "'WIP' not in labels"
  unmet_status: pending
  explanation: "Work in progress"
- condition: "'- [ ]' not in body"
  unmet_status: failure
  explanation: "Please finish all the required checklist tasks"
#- condition: "'Travis*' in statuses.succeeded" # Not working yet
#  unmet_status: failure
#  explanation: "Tests must pass before review starts"
#- condition: "'stickler*' in statuses.succeeded"
#  unmet_status: failure
#  explanation: "Linter must pass before review starts"


notifications:
- when: pull_request.opened
  comment: |
    Hey @{{ author }}, thanks for the PR! The review will start once
    the tests, CI checks and PR requirements (see checklist in your PR) have passed.
- when: pullapprove.approved
  if: "author_association == 'CONTRIBUTOR'"
  comment: "The review is completed. Thanks @{{ author }}, we'll take it from here."

groups:
  integrathors:
    conditions:
    - "'IntegraTHORs' in labels"
    reviews:
      required: 1  # 1 approval from this group are required
      request: 2  # 2 reviews requests will be sent at a time
      request_order: shuffle  # reviewers will be chosen in a random order
    reviewers:
      teams:
      - integrathors

  loki:
    conditions:
    - "'Loki' in labels"
    reviews:
      required: 1  # 1 approval from this group are required
      request: 2  # 2 reviews requests will be sent at a time
      request_order: shuffle  # reviewers will be chosen in a random order
    reviewers:
      teams:
      - loki

  client-core:
    conditions:
    - "'Loki' not in labels and 'IntegraTHORs' not in labels"
    # not created by a bot
    - "'schul-cloud-bot' not in author.username"
    reviewers:
      teams:
      - client-core
      - client-team
    reviews:
      required: 1  # number of approvals required from this group
      request: 1  # number of review requests sent at a time
      request_order: shuffle

  ux-core:
    conditions:
    - "'**/*.hbs' in files or 'static/styles/**/*.scss' in files or '.pullapprove.yml' in files"
    # only review if "**/*.hbs", "static/styles/**/*.scss" files or ".pullapprove.yml" have been touched
    reviewers:
      teams:
      - ux-core
    reviews:
      required: 1  # number of approvals required from this group
      request: -1  # request from all members a review
