#########################
## Sass Linter Config
#########################

# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html' (output format)
  #formatter: html
  # Output file
  #output-file: './sass-lint.html'
  # Raise an error if more than 50 warnings are generated
  max-warnings: 1

# File Options
files:
  include: 'static/styles/**/*.s+(a|c)ss'
  ignore:
    - 'static/styles/lib/bootstrap/**/*.s?(a|c)ss'
    - 'static/styles/lib/chosen/**/*.s?(a|c)ss'
    - 'static/styles/lib/spectrum/**/*.s?(a|c)ss'
    - 'static/styles/**/*.min.s?(a|c)ss'

# Linter rules
# Details: https://github.com/sasstools/sass-lint/tree/master/docs/rules
rules:
  bem-depth: 0
  border-zero:
    - 1
    - convention: zero
  brace-style: 1
  clean-import-paths:
    - 0
    - filename-extension: false
      leading-underscore: true
  empty-line-between-blocks: 0
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline: 1
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 1
    - allow-leading-underscore: true
      convention: camelcase
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  indentation:
    - 1
    - size: 2
  leading-zero:
    - 1
    - include: false
  mixin-name-format:
    - 0
    - allow-leading-underscore: true
      convention: camelcase
  mixins-before-declarations: 1
  nesting-depth: 0
  no-color-keywords: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-trailing-zero: 1
  no-vendor-prefixes: 1
  placeholder-name-format:
    - 1
    - allow-leading-underscore: true
      convention: camelcase
  property-sort-order:
    - 1
    - order: concentric
  quotes:
    - 1
    - style: double
  shorthand-values: 1
  single-line-per-selector: 0
  space-after-bang:
    - 1
    - include: false
  space-after-colon:
    - 1
    - include: true
  space-after-comma:
    - 1
    - include: true
  space-before-bang:
    - 1
    - include: true
  space-before-brace:
    - 1
    - include: true
  space-before-colon: 1
  trailing-semicolon: 1
  url-quotes: 1
  variable-name-format:
    - 1
    - allow-leading-underscore: true
      convention: camelcase
  zero-unit: 1