files:
  include: static/styles/**/*.s+(a|c)ss
  ignore:
    - static/styles/lib/bootstrap/**
    - static/styles/lib/chosen/**
    - static/styles/lib/spectrum/**
    - static/styles/**/*.min.s?(a|c)ss
syntax:
    include:
      - scss
      - sass
resolvers:
  attribute-quotes: 1
  border-zero: 1
  empty-line-between-blocks: 1
  final-newline: 1
  hex-length: 1
  hex-notation: 1
  indentation: 1
  no-color-keywords: 1
  no-css-comments: 0
  no-important: 0
  no-trailing-zero: 1
  property-sort-order: 1
  space-after-bang: 1
  space-after-colon: 1
  space-before-bang: 1
  space-before-colon: 1
  url-quotes: 1
  zero-unit: 1
options:
  optOut: false
