/* eslint-disable max-len */

const sectionTypes = ['standard', 'primary', 'standard', 'accent'];

module.exports = [
	{
		name: 'Gremium und Projektleitung',
		size: 'standard',
		team: [
			{
				title: 'Prof. Dr.',
				firstName: 'Christoph',
				lastName: 'Meinel',
				position: 'Projektleiter HPI Schul-Cloud und CEO des HPI',
				description: 'Christoph Meinel (Univ.-Prof., Dr. sc. nat., Dr. rer. nat., 1954) ist wissenschaftlicher Direktor und Geschäftsführer des <a href="http://hpi.de/" target="_blank">Hasso-Plattner-Instituts für Softwaresystemtechnik GmbH</a> (HPI). Christoph Meinel ist ordentlicher Professor (C4) für Informatik und hat den Lehrstuhl für <a href="http://hpi.de/meinel/lehrstuhl.html" target="_blank">Internet-Technologien und Systeme</a>  am HPI inne. Seine besonderen Forschungsinteressen liegen in den Bereichen Internet- und Informationssicherheit und Web 3.0: Semantic, Social, Service Web, sowie im Bereich innovativer Internetanwendungen und Systeme, vor allem zum e-Learning & Tele-Teaching und zur Telemedizin. Daneben ist er aktiv in der Innovationsforschung rund um die Stanforder Innovationsmethode des Design Thinking. Frühere Forschungsinteressen lagen im Bereich der theoretischen Grundlagen der Informatik in den Gebieten Komplexitätstheorie und effiziente OBDD-basierte Algorithmen und Datenstrukturen.<br><br>Christoph Meinel lehrt am HPI in den Bachelor- und Masterstudiengängen "IT-Systems Engineering" und in der School of Design Thinking. Er bietet MOOCs an auf der openHPI-Plattform und betreut zahlreiche Doktoranden. Zudem ist er Honorarprofessor an der Informatik-Fakultät der Technischen Universität Peking und lehrt als Gastprofessor an der Shanghai Universität. An der Universität Luxembourg ist er Research Fellow am <a href="http://wwwde.uni.lu/snt" target="_blank">interdisziplinären Zentrum</a>  (SnT). Zusammen mit Prof. Larry Leifer von der Stanford University ist er Programmdirektor des <a href="http://hpi.de/de/dtrp/programm/uebersicht.html" target="_blank">HPI-Stanford Design Thinking Research Programms</a>.<br><br>Christoph Meinel ist Autor bzw. Co-Autor von 9 <a href="http://hpi.de/meinel/publikationen/books.html?L=0" target="_blank">Büchern</a>  und 4 Anthologien sowie diversen Tagungsbänden. Er hat mehr als 400 wissenschaftliche Arbeiten in angesehenen wissenschaftlichen Journalen und auf internationalen Konferenzen veröffentlicht. Darüber hinaus ist er Herausgeber der elektronischen Fachzeitschriften ECCC – Electronic Colloquium on Computational Complexity, ECDTR - Electronic Colloquium on Design Thinking Research, des <a href="https://it-gipfelblog.hpi-web.de/" target="_blank">IT-Gipfelblogs</a>  und des <a href="http://www.tele-task.de/" target="_blank">tele-TASK-Archivs</a>.',
				pictureUrl: '/images/team/Christoph_Meinel.png',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: '25vh',
			},
			{
				title: 'Dr.',
				firstName: 'Niki',
				lastName: 'Sarantidou',
				position: 'Geschäftsführerin MINT-EC',
				description: 'Niki Sarantidou ist Geschäftsführerin des nationalen Excellence-Schulnetzwerks MINT-EC. Ihr politikwissenschaftliches Studium und ihre Promotion drehten sich hauptsächlich um die europäische Integration und die Wirksamkeit europäischer Institutionen. Sie war 12 Jahre Leiterin des Studienförderwerks Klaus Murmann der Stiftung der Deutschen Wirtschaft.<br>Seit 2011 befasst sie sich bei MINT-EC mit der Optimierung der MINT-Bildung an Schulen mit Sekundarstufe II. Schul- und Unterrichtsentwicklung sowie Studien- und Berufsorientierung gehören genauso zu ihren Arbeitsfeldern wie die Berücksichtigung wissenschaftlicher und technologischer Entwicklungen an Schulen, die Schülerinnen und Schüler auf ihrem Weg in die berufliche Zukunft unterstützen können.<br>Im Rahmen der HPI Schul-Cloud ist sie die Projektleiterin von Seiten MINT-EC und zuständig für die konzeptionelle Entwicklung der Cloud-Strukturen.',
				pictureUrl: '/images/team/Niki_Sarantidou.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Wolfgang',
				lastName: 'Gollub',
				position: 'Vorstandsvorsitzender MINT-EC',
				description: 'Wolfgang Gollub ist seit 2009 Vorstandsvorsitzender des nationalen Excellence-Schulnetzwerks <a href="https://mint-ec.de" target="_blank">MINT-EC</a> und Leiter der Nachwuchssicherung des Arbeitgeberverbandes <a href="https://gesamtmetall.de" target="_blank">Gesamtmetall</a>. Er hat Erwachsenenbildung und Politikwissenschaften an der Helmut-Schmidt-Universität in Hamburg studiert und ist nach zwölf Jahren als Bundeswehroffizier seit 1989 bei Gesamtmetall tätig. Dort hat er die nachwuchssichernde Öffentlichkeitsarbeit für die <a href="http://meberufe.info" target="_blank">Metall- und Elektro-Industrie</a>, die Ingenieur-Kampagne <a href="https://think-ing.de" target="_blank">think ING</a>, sowie die breit angelegte MINT-Förderung des Verbandes aufgebaut. Die Steigerung des Mädchenanteils in naturwissenschaftlichen und technischen Studiengängen und Berufen sowie die Digitalisierung in der Bildung sind ihm dabei besondere Anliegen, die er auch in einer Reihe von ehrenamtlichen Funktionen im MINT-Bereich verfolgt.<br>In seiner Freizeit ist er seit vielen Jahren als begeisterter Marathonläufer in aller Welt unterwegs, reist und fotografiert gern.',
				pictureUrl: '/images/team/Wolfgang_Gollub.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
		],
	},
	{
		name: 'Projektkoordination und wissenschaftliche Mitarbeiter',
		size: 'standard',
		style: 'primary',
		team: [
			{
				subheader_before: 'Hasso-Plattner-Institut',
				title: '',
				firstName: 'Jan',
				lastName: 'Renz',
				position: 'Technischer Leiter, HPI',
				description: 'Bevor er die akademische Laufbahn als Diplom Medieninformatiker (Beuth Hochschule) einschlug, arbeitete er über 10 Jahre als CTO einer Internetagentur. Seit 6 Jahren unterrichtet er Studenten sowohl on-, als auch offline. 2013 kam er zum Web Research Team des HPI und arbeitet seitdem daran, die Lernerfahrung in MOOCs zu verbessern. Seine Forschung konzentriert sich auf die nutzerzentrierte Optimierung von großen E-Learning Anwendungen. Zuletzt veröffentlichte er Forschungsberichte zu mobilem Lernen, Gamification, interaktiven Programmieraufgaben, sozialem Lernen und Learning Analytics. Darüber hinaus entwickelt er auch aktiv Open Source. Im Projekt HPI Schul-Cloud ist er als technischer Leiter für die Koordination und Vision rund um die Technik zuständig. Zudem betreut der die Mitarbeiter und Studierenden.<br> In seiner Freizeit joggt und musiziert er gerne oder setzt DIY Projekte um. Außerdem veranstaltet er den Berliner Ableger der "Nerd Nite", einer weltweiten Vortragsreihe, die es bereits in mehr als 90 Städten gibt und die unter dem Motto "Discovery Channel with beer" steht.',
				pictureUrl: '/images/team/Jan_Renz.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Catrina',
				lastName: 'John',
				position: 'Projektkoordinatorin, HPI',
				description: 'Catrina hat einen Masterabschluss der Freien Universität Berlin in Soziologie und ist Projektkoordinatorin der Projekt HPI Schul-Cloud. Im Rahmen ihrer Promotion beschäftigt sie sich mit Gender Diversity im Rahmen digital unterstützter Bildung. Einen Großteil ihrer Freizeit verbringt sie im Tischtennisverein.',
				pictureUrl: '/images/team/Catrina_John.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Matthias',
				lastName: 'Luderich',
				position: 'Chief Operating Officer, HPI',
				description: 'Matthias ist Politikwissenschaftler (M.A.) und hat sich als Berater vor allem mit den politischen Seiten der digitalen Transformation im Bildungsbereich befasst. Seit Juli 2018 ist er im Team zuständig für die politische Kommunikation. Wenn Matthias nicht gerade fasziniert den Berliner Politikkosmos verfolgt, spielt er beim USV Potsdam Regionalliga-Basketball oder verbringt seine Zeit im heimischen Garten.',
				pictureUrl: '/images/team/matthias_luderich.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Vivien',
				lastName: 'Malyska',
				position: 'Projektkoordinatorin, HPI',
				description: 'Vivien ist Erziehungswissenschaftlerin (M.A., Universität Potsdam) und übernimmt im Team die Projektkoordination. Neben ihren Aufgaben auf organisatorischer Ebene wirft sie auch aus bildungswissenschaftlicher Perspektive einen Blick auf die HPI Schul-Cloud. In ihrer Freizeit findet man sie meistens auf dem Volleyballfeld oder im Grünen.',
				pictureUrl: '/images/team/Vivien_Malyska.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Falko',
				lastName: 'Benthin',
				position: 'Wissenschaftlicher Mitarbeiter, HPI',
				description: 'Falko hat an der HTW Berlin sein Bachelor- und Masterstudium absolviert und anschließend mehrere Jahre im Ops-Team eines namhaften Hosters zugebracht. Jetzt unterstützt er das HPI Schul-Cloud-Team als System-Engineer DevOps. In seiner Freizeit bespaßt er seine Kinder, liest und engagiert sich im HochDrei - Bilden und Begegnen in Brandenburg e.V.',
				pictureUrl: '/images/team/Falko_Benthin.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Dominik',
				lastName: 'Brüchner',
				position: 'Wissenschaftlicher Mitarbeiter, HPI',
				description: 'Dominik war vor seinem BSc in Medieninformatik an der Technischen Hochschule Nürnberg in der Softwareentwicklung bei der Datev eG in Nürnberg tätig. Nach seinem Bachelorstudium führte ihn seine Leidenschaft für Bildung und E-Learning an das Berliner MOOC Startup Iversity.org. Seine Leidenschaft für nutzerzentrierte Produkte und digitale Bildungstechnologien führte ihn während seines Masterstudiums Computer Science & HCI an der TU Berlin an die School of Design Thinking des HPI, bei der er auch erstmals konzeptionell an der HPI Schul-Cloud mitwirken konnte. Im Team arbeitet er an Strategien zur Erhöhung der Nutzerakzeptanz und Verbesserung des Lernerlebnisses. Weiterhin koordiniert er die Weiterentwicklung der UX. In seiner Freizeit trifft man ihn auf Reisen, beim Klettern, Wassersport oder Parkour im urbanen Dschungel.',
				pictureUrl: '/images/team/Dominik_Brüchner.jpg',
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Cedric',
				lastName: 'Evers',
				position: 'Wissenschaftlicher Mitarbeiter, HPI',
				description: 'Cedric Evers war 7 Jahre am GeoForschungsZentrum in Potsdam, unter anderem als Entwickler und Ausbilder tätig. Er ist seit Juli 2018 im HPI Schul-Cloud Team im Client & Server-Bereich tätig. Privat liebt er es gesunde Sachen zu kochen und seine Freizeit mit analogen Büchern, Sport und Familie zu verbringen.',
				pictureUrl: '/images/team/cedric_evers.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Thomas',
				lastName: 'Feldtkeller',
				position: 'Wissenschaftlicher Mitarbeiter, HPI',
				description: 'Thomas hat sein Bachelorstudium am HPI abgeschlossen und entwickelt seit November 2017 die HPI Schul-Cloud mit, zunächst als Praktikant und seit Oktober 2018 als wissenschaftlicher Mitarbeiter. Er kümmert sich unter anderem um die Verarbeitung von Daten im Backend und baut Schnittstellen zu anderen Systemen. Privat jongliert er und spielt kompetitiv sowie kooperativ Videospiele.',
				pictureUrl: '/images/team/thomas_feldtkeller.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Tormod',
				lastName: 'Flesjø',
				position: 'Wissenschaftlicher Mitarbeiter, HPI',
				description: 'Tor ist ein norwegischer Softwareentwickler und lebt seit 2018 in Deutschland. Ursprünglich ist er Therapeut, hat jedoch durch seine Leidenschaft für Technologie die Karriere gewechselt und Development in Berlin studiert. Im Projekt HPI Schul-Cloud kümmert er sich um die Datenverarbeitung und Codesicherheit im Backend. In seiner Freizeit geht er gerne ins Fitnessstudio und spielt Schach.',
				pictureUrl: '/images/team/tormod_flesjo.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Maximilian',
				lastName: 'Grundke',
				position: 'Wissenschaftlicher Mitarbeiter, HPI',
				description: 'Maximilian hat sein Bachelor- und Master-Studium am Hasso-Plattner-Institut absolviert. Er engagiert sich seitdem als Gründer im Bereich Mental Healthcare und unterstützt das Projekt HPI Schul-Cloud seit Oktober 2018 in der Softwareentwicklung. In seiner Freizeit beschäftigt sich Maximilian mit Geschichte und ist eine Bereicherung für jedes Trivia-Team.',
				pictureUrl: '/images/team/Max_Grundke.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Sebastian',
				lastName: 'Hirsch',
				position: 'Community Manager, HPI',
				description: 'Sebastian ist seit März 2019 im Team der HPI Schul-Cloud tätig. Als Community Manager pflegt er den Austausch mit allen Nutzer*innen und Interessierten im Netz. Zuvor hat er als Bildungsaktivist, Veranstaltungsmanager und Schulbauberater gearbeitet. An der Jacobs University hat er Integrated Social Sciences studiert. Seine Freizeit verbringt er auf dem Rad, beim Bouldern oder in Hamburg.',
				pictureUrl: '/images/team/Sebastian_Hirsch.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Adrian',
				lastName: 'Jost',
				position: 'Wissenschaftlicher Mitarbeiter, HPI',
				description: 'Adrian hat am Hasso-Plattner-Institut IT-Systems Engineering studiert und ist im Projekt HPI Schul-Cloud unter anderem für Architekturfragen aber auch für UI und die UX zuständig. Zudem war er Teil des Bachelorprojekts 2018/2019 der HPI Schul-Cloud. Privat hat er seinen Ausgleich im Rennrad fahren und Mountainbiken gefunden.',
				pictureUrl: '/images/team/Adrian_Jost.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
					github: 'https://github.com/adrianjost',
					website: 'https:/adrianjost.dev',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Konstantin',
				lastName: 'Kaiser',
				position: 'Wissenschaftlicher Mitarbeiter, HPI',
				description: 'Konstantin hat Lehramt mit den Fächern Musik und Deutsch an der Universität Potsdam studiert. Beim Axel Springer Verlag arbeitete er sieben Jahre als Produktentwickler an der Schnittstelle zwischen Redaktion und Technik. Die wissenschaftliche Mitarbeit an der HPI Schul-Cloud führt ihn wieder zurück in die Welt der Lehrer*innen und Schüler*innen, wo er als PO (Product Owner) zwischen den Usern und der technischen Umsetzung vermittelt und übersetzt. Dabei motiviert es ihn, seiner als Lehrerin arbeitenden Frau und künftig auch seinen Kindern den Schulalltag zu erleichtern. In seiner Freizeit ist er stets auf der Suche nach guter Musik, entspannt aktiv auf dem Rennrad und bei der Gartenarbeit. Alltagsdinge regelt er gerne online, um mehr Zeit offline mit Familie und Freunden zu verbringen.',
				pictureUrl: '/images/team/Konstantin_Kaiser.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Alexander',
				lastName: 'Kremer',
				position: 'Wissenschaftlicher Mitarbeiter, HPI',
				description: 'Alex hat Angewandte Informatik an der HTW Berlin im Master studiert und ist im Projekt HPI Schul-Cloud als wissenschaftlicher Mitarbeiter tätig. Hier programmiert er an diversen Diensten und sorgt unter anderem dafür, dass externe Inhalte in die HPI Schul-Cloud kommen. Neben der Arbeit stehen sein Hund Dexter und das neu gewonnene Hobby Segeln im Fokus.',
				pictureUrl: '/images/team/Alexander_Kremer.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Sophie',
				lastName: 'Krüger',
				position: 'Wissenschaftliche Mitarbeiterin, HPI',
				description: 'Sophie studiert Englisch und LER auf Lehramt im Master an der Universität Potsdam. Im Team HPI Schul-Cloud unterstützt sie das Team bei pädagogischen und didaktischen Fragen. Weiterhin koordiniert sie die bildungswissenschaftliche Begleitforschung, den User-Support und das Onboarding der Schulen. In ihrer Freizeit entspannt sie gern mit einem guten Buch, kocht oder reist durch virtuelle Welten.',
				pictureUrl: '/images/team/sophie_krueger.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Arne',
				lastName: 'Oberländer',
				position: 'Educational Knowledge Engineer, HPI',
				description: 'Arne ist Physiker (Diplom, TU Berlin) und war bisher Physikdidaktiker und Produktentwickler einer Reihe von Web- und Elearning-Projekten. Er managt im Team der HPI Schul-Cloud das Content-Angebot von der ersten Idee bis zur Tür der Entwickler. Privat engagiert er sich im Projekt "Schulkontext.de", spielt Volleyball, oder programmiert erfrischende Synthesizersounds.',
				pictureUrl: '/images/team/Arne_Oberländer.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Wolfgang',
				lastName: 'Rathgeb',
				position: 'Wissenschaftlicher Mitarbeiter, HPI',
				description: 'Wolfgang hat seinen Master in technischer Informatik Ende März 2019 abgeschlossen und ist seit dem als Full-Stack-Entwickler Teil des HPI Schul-Cloud Teams. Dabei ist sein Ziel Vorgänge so einfach wie möglich zu halten und möglichst viele Schritte zu Automatisieren. Das spiegelt sich auch in seiner Freizeit wieder, in der er gerne viele alltägliche Aufgaben automatisiert, um das Komfortlevel zu steigern und mehr Zeit für neue Projekte zu haben – aktuell seinen Garten.',
				pictureUrl: '/images/team/Wolfgang_Rathgeb.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Sarah',
				lastName: 'Schäfer',
				position: 'Wissenschaftliche Mitarbeiterin, HPI',
				description: 'Als ökosoziale Designerin (Masterabschluss an der Freien Universität Bozen) und Design-Thinkerin (Zusatzstudium am HPI) möchte Sarah ihre Fähigkeiten nutzen, um zu einem gesellschaftlichen Wandel, der Mensch und Umwelt dienlich ist, beizutragen. Deshalb ist Ihre Vision für die HPI Schul-Cloud, jungen Menschen, selbstbestimmtes Lernen zu ermöglichen. Im Team arbeitet sie als User Experience - und User Interface Designerin und sorgt für die Verbesserung der Nutzerfreundlichkeit und des Lernerlebnisses. Ihre Freizeit widmet Sarah der Kreativität, welche Ausdruck im Kochen, Designen oder Malen findet.',
				pictureUrl: '/images/team/sarah_schaefer.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Luisa',
				lastName: 'Schrott',
				position: 'Wissenschaftliche Mitarbeiterin, HPI',
				description: 'Luisa hat bereits als Designerin für die Aachener Agentur Polarstern Education gearbeitet und dort digitale Bildungsformate konzipiert und umgesetzt. Umso mehr freut sie sich jetzt Teil des Frontend Development Teams der HPI Schul-Cloud zu sein, um digitales Lernen und Lehren an deutschen Schulen weiter vorantreiben zu können. Mit ihrer Begeisterung für UX / UI wuchs auch die Neugier am Programmieren, was der Grund für sie war am 9 wöchigen Web Development Bootcamp Ironhack in Berlin teilzunehmen. In der Freizeit trifft man Luisa auf ihrer Yogamatte, in fernen Ländern oder beim Kochen mit Freunden.',
				pictureUrl: '/images/team/luisa_schrott.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Hannes',
				lastName: 'Schurig',
				position: 'Wissenschaftlicher Mitarbeiter, HPI',
				description: 'Hannes hat Bachelor Medieninformatik an der Beuth Hochschule für Technik in Berlin studiert. Nach 10 Jahren als IT-Administrator folgte nun der thematische Wechsel zum Entwickler am HPI. Seit Mitte April 2018 ist er im Team HPI Schul-Cloud im Client-/Server-Bereich tätig. Privat versucht Hannes mit Sport und etwas gesunder Ernährung das Klischee eines klassischen ITlers zu widerlegen. Außerdem bemüht er sich, seinen Blog unter it-stack.de regelmäßig mit Inhalten zu versorgen.',
				pictureUrl: '/images/team/Hannes_Schurig.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Florian',
				lastName: 'Sittig',
				position: 'Wissenschaftlicher Mitarbeiter, HPI',
				description: 'Florian hat Lehramt für die Sprachen Englisch und Spanisch studiert und arbeitete bereits über 10 Jahre privat, institutionell und an diversen Schulen als Lehrkraft. Seit Mitte Juli ist er nun Teil unseres Teams und hilft dabei, die HPI Schul-Cloud bestmöglich in den modernen Unterricht zu integrieren. In der Digitalisierung sieht er Chancen für mehr Austausch und Kooperation zwischen den Lehrkräften. In seiner Freizeit trifft er sich gerne mit Freunden, geht wandern und hat eigentlich immer verschiedene Projekte nebenher, an denen er gerade arbeitet.',
				pictureUrl: '/images/team/Florian_Sittig.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Jacqueline',
				lastName: 'Thorns',
				position: 'Wissenschaftliche Mitarbeiterin, HPI',
				description: 'Jacqueline hat European Studies an der Europa-Universität Viadrina im Master studiert und ist im Projekt HPI Schul-Cloud als wissenschaftliche Mitarbeiterin für das Eventmanagement und den Datenschutz zuständig. Privat entspannt sie gerne in der Natur oder bei einem guten Buch.',
				pictureUrl: '/images/team/Jacqueline_Thorns.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Ramona',
				lastName: 'Weitzenberg',
				position: 'Wissenschaftliche Mitarbeiterin',
				description: 'Mona gestaltet. Mit Menschen. Für Menschen. Durch ihre 15-jährige Praxis als freiberufliche Designerin, konnte sich Mona neben einem immensen Erfahrungsschatz und kreativer Routine ein multidisziplinäres Gestaltungsportfolio erarbeiten, dass sowohl die klassischen als auch die neuen Medien umfasst. Eine Gestaltung einer Broschüre erfährt die gleiche Hingabe wie die Entwicklung einer komplexen Applikation. Seit November 2018 unterstützt sie das Team der HPI Schul-Cloud in allen Gestaltungsfragen als Art Direktorin. Dabei liegt der Kern ihrer Arbeit im Interfacedesign (UI/UX) und in der Erarbeitung einer durchgehenden Corporate Identity. Familie, Hund und Haus sind für Mona nötiger Ruhepol, Erdung, Inspiration und kreative Neuerfindung zugleich.',
				pictureUrl: '/images/team/ramona_weitzenberg.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Tobias',
				lastName: 'Wollowski',
				position: 'Wissenschaftlicher Mitarbeiter',
				description: 'Tobias hat vor seinem Master-Studium am HPI an der Technischen Hochschule in Brandenburg Applied Computer Science studiert. Während seines Studiums konzentrierte er sich auf Verteilte Systeme und verbrachte ein Semester an der German Jordanian University in Amman, Jordanien.<br>Am HPI vertiefte er u.a. sein Wissen über Progressive-Web-Apps und Page-Speed-Optimization und moderne Web-Technologien. Im Projekt HPI Schul-Cloud schreibt er derzeit seine Masterarbeit und forscht an Strategien zur Offline-Verfügbarkeit von Web-Anwendungen und Peer-2-Peer Technologien.<br>In seiner Freizeit trainiert Tobias im Potsdamer Seglerverein Kinder und Jugendliche im Segeln.',
				pictureUrl: '/images/team/Tobias_Wollowski.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Sophie',
				lastName: 'Plötz',
				position: 'Projektkoordination, MINT-EC',
				description: 'Sophie absolvierte ihr Masterstudium in British Studies (HU Berlin) und ist zusätzlich staatlich geprüfte Kulturmanagerin (Deutsche Akademie für Management, Berlin). Seit Juli 2018 wirkt sie im Projekt HPI Schul-Cloud mit und übernimmt seit November 2019 die operative Projektleitung des Roll-Outs an die MINT-EC-Schulen. Dort koordiniert sie die Mitgestaltung der Lehrkräfte im Pilotprojekt. Nach dem Masterabschluss begleitete Sophie die Einführung einer digitalen Lernplattform und war in deren administrativer Betreuung sowie in der Konzeption von E-Learning-Inhalten tätig. Zum Ausgleich spielt sie Trompete im Blasorchester, besucht Museen, liest und reist gern.',
				pictureUrl: '/images/team/Sophie_Plötz.JPG',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				subheader_before: 'Das nationale Excellence-Schulnetzwerk MINT-EC',
				title: '',
				firstName: 'Sigrid',
				lastName: 'Stobbe',
				position: 'Projektkoordination, MINT-EC',
				description: 'Sigrid ist Bildungswissenschaftlerin (M.A., Freie Universität Berlin) und im Mai 2018 als konzeptionelle Mitarbeiterin im Projekt HPI Schul-Cloud auf Seiten von MINT-EC gestartet. Seit November 2018 übernimmt sie die operative Projektleitung des Roll-Outs an 316 MINT-EC-Schulen, koordiniert die Mitgestaltung der Lehrkräfte im Pilotprojekt und treibt die konzeptionelle Weiterentwicklung der HPI Schul-Cloud voran. Vor ihrem Masterabschluss arbeitete Sigrid in der Qualitätsentwicklung & Evaluation in der Fort- und Weiterbildung von Erwachsenen und forschte in verschiedenen Bildungsbereichen zur Qualität in Lern- und Bildungsprozessen (offline und online). Außerhalb der Arbeitszeit verbringt sie viel Zeit in den Boulder- und Kletterhallen ihrer Heimatstadt Berlin und sucht sportlichen Ausgleich beim Yoga.',
				pictureUrl: '/images/team/Sigrid_Stobbe.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Franziska',
				lastName: 'Beyer',
				position: 'Konzeptionelle Mitarbeiterin, MINT-EC',
				description: 'Franziska ist Politikwissenschaftlerin mit Schwerpunkt Bildungspolitik und Didaktik (M.A., Freie Universität Berlin). Als Teambuilding-Trainerin für Schulklassen arbeitete Sie über mehrere Jahre eng mit Lehrern und Schülern zusammen. Seit Januar 2020 betreut sie als konzeptionelle Mitarbeiterin bei MINT-EC gemeinsam mit Rasmus, Sophie und Severine die Pilotschulen. Durch den engen Kontakt zu Lehrkräften und Schüler:innen stellen sie sicher, dass die Expertise der tatsächlichen Nutzer:innen in die Entwicklung der HPI Schul-Cloud einbezogen wird. In ihrer Freizeit findet man Franziska mit Farbe bekleckst vor einer Leinwand, außer Atem beim Stockkampf oder in irgendwelchen Ländern, deren Namen die meisten noch nie gehört haben.',
				pictureUrl: '/images/team/franziska_beyer.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Rasmus ',
				lastName: 'Geßner',
				position: 'Konzeptioneller Mitarbeiter, MINT-EC',
				description: 'Rasmus ist seit November 2018 konzeptioneller Mitarbeiter bei MINT-EC und betreut u.a. gemeinsam mit Sophie die Pilotschulen. Er bringt neben seinem Studium der Soziologie und Kulturwissenschaften (M.A., Europa-Universität Viadrina, Frankfurt /Oder) vier Jahre Erfahrungen in der universitären Erwachsenenbildung mit und entwickelte bei einem Berliner Bildungsträger eine e-Learning-Lernplattform. Außerhalb des Büros zieht es ihn in die nächstgelegene Boulderhalle, in Parks zum Joggen, zur nächsten Chorprobe oder gen Skandinavien.',
				pictureUrl: '/images/team/Rasmus_Gessner.png',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Kira',
				lastName: 'Kötter',
				position: 'Konzeptionelle Mitarbeiterin, MINT-EC',
				description: 'Kira absolvierte nach ihrem Masterstudium der französischen Literaturwissenschaft in Hamburg und Bordeaux ein Volontariat im Bereich Kommunikation. Nachdem sie daraufhin eine Online-Community für Fremdsprachenlernende redaktionell betreute, ist sie nun für Öffentlichkeitsarbeit und Community Management für die HPI Schul-Cloud bei MINT-EC tätig',
				pictureUrl: '/images/team/kira_koetter.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Severine',
				lastName: 'Sarközi',
				position: 'Konzeptionelle Mitarbeiterin, MINT-EC',
				description: 'Severine unterstützt seit Januar 2020 das Projekt HPI-Schul-Cloud als konzeptionelle Mitarbeiterin und in der Organisation. Ihren Bachelor in Deutscher Philologie und Sozial- und Kulturanthropologie hat sie an der FU Berlin abgeschlossen. Durch ihre Arbeit an einer Schule konnte sie einige praktische Erfahrung im Bildungssystem sammeln – so hat sie ihr Interesse an digitaler Bildung entdeckt. Nach einem Ausflug ins IT-Projektmanagement freut sie sich nun sehr darauf, Schulen auf ihrem Weg in die digitale Transformation zu unterstützen und beide Welten miteinander zu verbinden. Und weil sie findet, dass man nie zu alt ist, um etwas Neues zu lernen, hat sie kürzlich damit angefangen zu programmieren. Wenn ihr davon dann doch mal der Kopf raucht, entspannt sie sich gerne mit Yoga oder werkelt in ihrem Garten.',
				pictureUrl: '/images/team/severine_sarkoezi.JPG',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
		],
	},

	{
		name: 'Studierende',
		size: 'small',
		team: [
			{
				title: '',
				firstName: 'Josefine',
				lastName: 'Fogain',
				position: 'Studentische Hilfskraft',
				description: 'Josefine studiert Volkswirtschaftslehre und Spanische Philologie im Bachelor an der Universität Potsdam. Seit August 2019 unterstützt Sie das HPI Schul-Cloud Projekt in organisatorischen Aufgaben und im User Support. Privat reist sie gern und ist in der Natur unterwegs.',
				pictureUrl: '/images/team/josefine_fogain.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Marcel',
				lastName: 'Garus',
				position: 'Studentische Hilfskraft',
				description: 'Marcel Garus studiert Bachelor IT-Systems Engineering am HPI und entwickelt seit Mitte 2019 die Flutter-Version der HPI Schul-Cloud-App. Privat entwickelt er gerne OpenSource-Projekte, spielt Klavier und schaut mit anderen zusammen Serien auf Netflix.',
				pictureUrl: '/images/team/marcel_garus.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Dominik',
				lastName: 'Glandorf',
				position: 'Studentische Hilfskraft',
				description: 'Dominik ist Studentische Hilfskraft und war Teil des Bachelorprojekts 2017/18. Er studiert IT-Systems Engineering am HPI und kümmert sich in der HPI Schul-Cloud um Tools zur Content-Erstellung & -Integration. Privat tanzt er gerne Hip Hop und beschäftigt sich mit Philosophie und Politik.',
				pictureUrl: '/images/team/Dominik_Glandorf.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Dominik',
				lastName: 'Jaekel',
				position: 'Studentische Hilfskraft',
				description: 'Dominik war Teil des Bachelorprojektes 2017/2018, dort schrieb er Blogbeiträge und arbeitete am Content-Editor. Seit August 2018 ist er Studentische Hilfskraft und unterstützt bei der HPI Schul-Cloud-Entwicklung. Vor dem Informatikstudium war er ein Jahr für ein Studium Generale in Freiburg im Breisgau. In seiner Freizeit schreibt er gerne Geschichten und spielt Gitarre.',
				pictureUrl: '/images/team/Dominik_Jaekel.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Patricia',
				lastName: 'Rau',
				position: 'Studentische Hilfskraft',
				description: 'Patricia hat BWL-Digitale Wirtschaft an der Beuth Hochschule für Technik in Berlin studiert. Seit Mai 2019 unterstützt sie das HPI Schul-Cloud Projekt bei kommunikativen und organisatorischen Aufgaben. Ihre Freizeit verbringt sie gerne mit Freunden in Cafes oder draußen im Grünen. Außerdem reist und fotografiert sie gerne.',
				pictureUrl: '/images/team/patricia_rau.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Yulia',
				lastName: 'Shikhareva',
				position: 'Studentische Hilfskraft',
				description: 'Yulia studiert zurzeit im Bachelorprogramm Informatik/Computational Science am Institut für Informatik der Universität Potsdam. Zuvor erlangte sie in Moskau Bachelorgrad in Ökonomie. Seit April 2019 engagiert sie sich im Projekt HPI Schul-Cloud als Software-Testerin. In ihrer Freizeit genießt Yulia die Schönheiten der Natur und Städte Europas.',
				pictureUrl: '/images/team/Yulia.jpeg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Clemens',
				lastName: 'Tiedt',
				position: 'Studentische Hilfskraft',
				description: 'Clemens Tiedt studiert IT-Systems-Engineering im Bachelor und entwickelt die Flutter-App der HPI Schul-Cloud mit. In seiner Freizeit spielt er am liebsten Pen&Paper-Rollenspiele.',
				pictureUrl: '/images/team/clemens_tiedt.png',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Jonas',
				lastName: 'Wanke',
				position: 'Studentischer Mitarbeiter',
				description: 'Jonas studiert Bachelor IT-Systems Engineering am HPI und ist bereits seit seinem Schüler-Praktikum im Sommer 2017 unter anderem an der Entwicklung der HPI Schul-Cloud Android-App beteiligt. Im Oktober 2017 nahm er mit der Nationalmannschaft bei den WorldSkills (Berufsweltmeisterschaften) in Abu Dhabi im Skill 9: IT Software Solutions for Business teil und holte eine Bronzemedaille für Deutschland. Privat klettert und schwimmt er gerne.',
				pictureUrl: '/images/team/Jonas_Wanke.png',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
		],
	},
	{
		name: 'Weitere Mitarbeiter',
		size: 'small',
		team: [
			{
				title: '',
				firstName: 'Christian',
				lastName: 'Sommer',
				position: 'Praktikant',
				description: 'Christian hat dieses Jahr die Schule abgeschlossen und wollte nicht direkt studieren, wie viele andere, sondern erst praktische Erfahrung und Orientierung sammeln. Daher entschied er sich, auch dank Jugend forscht, für ein Praktikum am HPI im Team der HPI Schul-Cloud. Seine Aufgabenbereiche erstrecken sich von Frontend über UX/UI bis hin zum Backend. Privat verfolgt er eigene kleine Softwareprojekte und beschäftigt sich mit Mikrocontrollern und der Automatisierung des eigenen Zuhauses und täglichen Arbeitsabläufen. Außerdem verreist und fotografiert er gerne.',
				pictureUrl: '/images/team/christian_sommer.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},

		],
	},
	{
		name: 'Alumni',
		size: 'small',
		style: 'accent',
		team: [
			{
				title: '',
				firstName: 'Paul',
				lastName: 'Arndt',
				position: 'Ehem. Masterstudent',
				description: 'Paul hat seine Masterarbeit im Projekt HPI Schul-Cloud geschrieben. In seinem Studium konzentrierte er sich neben der Webentwicklung auf Design Thinking und Machine Learning. Für seine Masterarbeit beschäftigte er sich hauptsächlich mit Chancengleichheit in der Schule durch Binnendifferenzierung und kooperatives Lernen. Technisch bedeutete dies die Schaffung eines neuen Editors mit eingebauter Unterstützung für Gruppenarbeit und die in der Praxis angewandten didaktischen Methoden. Neben dem Studium schreibt Paul gerne an eigenen Geschichten oder erklettert die Boulderwände Berlins und Potsdams.',
				pictureUrl: '/images/team/paul_arndt.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Raoul',
				lastName: 'Baron',
				position: 'Ehem. Bachelorstudent',
				description: 'Raoul ist Teil des Bachelorprojekts 2017/18 und für IT-System Engineering am HPI eingeschrieben. Für die HPI Schul-Cloud ist er primär für die Pseudonymisierung zuständig. In der Vergangenheit hat er zudem einige Erfahrungen durch Start-Ups im Bereich von Schule gesammelt. In seiner Freizeit rappt er gerne und spielt Geige.',
				pictureUrl: '/images/team/Raoul_Baron.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Georg',
				lastName: 'Berecz',
				position: 'Ehem. Masterstudent',
				description: 'Georg schreibt derzeit seine Masterarbeit im Projekt HPI Schul-Cloud. Er befasst sich fachlich mit der Frage, wie kompetenz-basiertes Lernen in die HPI Schul-Cloud integriert werden kann. Technisch geht es dabei um die modulare Erweiterung von Microservice Architekturen. Sein Bachelorstudium hat Georg ebenfalls am HPI absolviert und anschließend hat er im Zuge seines Masterstudiums zwei Semester in Estland studiert. In seiner Freizeit schießt bzw. wirft er Bälle in Tore oder Körbe und malträtiert sein elektronisches Schlagzeug.',
				pictureUrl: '/images/team/Georg_Berecz.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Katharina',
				lastName: 'Blaß',
				position: 'Ehem. Bachelorstudentin',
				description: 'Katharina hat IT-Systems-Engineering im Bachelor am HPI studiert und unterstützte das HPI Schul-Cloud Team im Bereich Frontend. Zusätzlich war sie Teil des Bachelorprojektes 2018/19 bei der HPI Schul-Cloud. Neben Studium und Arbeit verbringt sie ihre Zeit gern sportlich aktiv und hat eine Leidenschaft für das Backen von Torten.',
				pictureUrl: '/images/team/Katharina_Blass.jpg',
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Carolin',
				lastName: 'Goerke',
				position: 'Ehem. Bachelorstudentin',
				description: 'Carolin studierte am Hasso-Plattner-Institut IT-Systems Engineering im Bachelor und war Teil des Bachelorprojektes 2018/19 bei der HPI Schul-Cloud. Privat arbeitet sie gerne mit Kindern und Jugendlichen zusammen. Außerdem tanzt sie gerne.',
				pictureUrl: '/images/team/Carolin_Goerke.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Carl',
				lastName: 'Gödecken',
				position: 'Ehem. Bachelorstudent',
				description: 'Carl war Mitglied des Bachlorprojektes 2016/2017, das aktiv an dem ersten Prototypen der HPI Schul-Cloud gearbeitet hat. Seine Bachelorarbeit trug den Titel: HPI Schul-Cloud for iOS: Adapting a browser-based learning platform for mobile devices.',
				pictureUrl: '/images/team/Carl_Gödecken.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Max',
				lastName: 'Haubold',
				position: 'Ehem. Bachelorstudent',
				description: 'Max war Teil des Bachelorprojekts 2017/2018 und beschäftigt sich mit Contenterstellung für Lehrkräfte. Nebenbei philosophiert er gerne über die Zukunft der Bildung inner- und außerhalb der Cloud. In seiner Freizeit macht er mit Freunden Musik, und ist auf der Suche nach Abenteuer, guten Büchern und Gott.',
				pictureUrl: '/images/team/Max_Haubold.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Ivan',
				lastName: 'Ilic',
				position: 'Ehem. Bachelorstudent',
				description: 'studierte am Hasso-Plattner-Institut IT-Systems Engineering im Bachelor und war Teil des Bachelorprojektes 2018/19 bei der HPI Schul-Cloud. Privat spielt er gerne Basketball und Tennis. Außerdem hört er liebend gerne Musik.',
				pictureUrl: '/images/team/Ivan_Ilic.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Michael',
				lastName: 'Janke',
				position: 'Ehem. Masterstudent',
				description: 'Michael hat seine Masterarbeit im Projekt HPI Schul-Cloud geschrieben. Nicht nur sein Studium am HPI, auch seine Erfahrungen durch die Tätigkeit an einem Gymnasium als Administrator und technischer Berater gingen mit in die Arbeit an der HPI Schul-Cloud ein. Dabei entstand die Idee der Entwicklung einer Ablagezone für nicht-formalisierte Interaktion. Bilder oder andere Medien sollen einfach in eine gemeinsame Ablage geteilt werden können. Auch sollen Inhalte einfach auf einer digitalen Tafel angezeigt werden können. In seiner Freizeit verbindet er sein Studium mit seinen handwerklichen Fähigkeiten. 3D-Drucken, Smart-Home, aber auch Hammer und Wasserwaage sind keine Fremdworte für ihn. Zum Ausspannen wandert Michael gerne in der Natur und sucht dafür immer neue Orte und Abenteuer.',
				pictureUrl: '/images/team/Michael_Janke.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Nayera',
				lastName: 'Kassem',
				position: 'Ehm. Studentin',
				description: 'Nayera studiert Networks Engineering an der Deutschen Universität in Kairo, Ägypten. Sie hat ihre Bachelorarbeit im Projekt HPI Schul-Cloud geschrieben und in diesem Kontext die Security-Aspekte und das Dateisystem analysiert. Ihre Freizeit verbringt sie mit Lesen, Reisen und ihren Freunden. Dabei freut sie sich stets interessante Leute zu treffen und neue Erfahrungen zu sammeln. ',
				pictureUrl: '/images/team/nayera_kassem.JPG',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Jonas',
				lastName: 'Keutel',
				position: 'Ehem. Masterstudent',
				description: 'Jonas hat seine Masterarbeit im Projekt HPI Schul-Cloud geschrieben. Der Schwerpunkt in seinem Studium liegt neben der Webentwicklung in letzter Zeit immer mehr auf dem Design Thinking. Die Idee hinter seiner Masterarbeit ist Lehrer bei der Planung und vor allem dem Teilen ihrer Unterrichtsstunden sowie Unterrichtsreihen zu unterstützen. Durch eine Bereitstellung der Unterrichtsplanung kann eine Diskussion sowie eine Mix-and-Match-Mentalität hervorgerufen werden, die der Qualität des Unterrichts nur guttun kann. Abseits des Studiums findet man Jonas meistens auf Fußballplätzen oder auf der Suche nach neuen Reisezielen. ',
				pictureUrl: '/images/team/Jonas_Keutel.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Niklas',
				lastName: 'Kiefer',
				position: 'Ehem. Bachelorstudent',
				description: 'Niklas hat IT-Systems Engineering am HPI studiert und war Teil des Bachelorprojekts 2016/2017 der HPI Schul-Cloud und war somit seit Beginn der Anwendung involviert. Nach dem Studium am HPI arbeitete er bis August 2018 am Frontend und Backend, sowie gelegentlich an der Android-App der HPI Schul-Cloud. Seine größten Hobbies sind Fußball und Musik.',
				pictureUrl: '/images/team/Niklas_Kiefer.png',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Juliane',
				lastName: 'Kleinknecht',
				position: 'Ehem. Bachelorstudentin',
				description: 'Juliane arbeitete für das Bachelorprojekt 2017/2018. Dort war sie verantwortlich für die Integration und die Funktionalitäten des Content-Editors. Ansonsten ist sie sportlich aktiv und spielt am liebsten Tennis.',
				pictureUrl: '/images/team/Juliane_Kleinknecht.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Nico',
				lastName: 'Knoll',
				position: 'Ehem. Bachelorstudent',
				description: 'Nico war Mitglied des Bachlorprojektes 2016/2017, das aktiv an dem ersten Prototypen der HPI Schul-Cloud gearbeitet hat. Seine Bachelorarbeit trug den Titel: Using Embedded React to enable complex yet performant web applications.',
				pictureUrl: '/images/team/Nico_Knoll.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Hannes',
				lastName: 'Kohlsaat',
				position: 'Ehem. Bachelorstudent',
				description: 'Hannes studierte am Hasso-Plattner-Institut IT-Systems Engineering im Bachelor und war Teil des Bachelorprojektes 2018/19 bei der HPI Schul-Cloud. Privat geht er gerne laufen und interessiert sich sehr für Wirtschaftsthemen. Außerdem ist er seit Beginn seines Studiums Mitglied im Chor der Universität Potsdam.',
				pictureUrl: '/images/team/Hannes_Kohlsaat.jpg',
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'David',
				lastName: 'Kreidler',
				position: 'Ehem. Bachelorstudent',
				description: 'David war Mitglied des Bachlorprojektes 2016/2017, das aktiv an dem ersten Prototypen der HPI Schul-Cloud gearbeitet hat. Seine Bachelorarbeit trug den Titel: Making User flow and User interface on Education Sites efficient.',
				pictureUrl: '/images/team/David_Kreidler.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Nicco',
				lastName: 'Kunzmann',
				position: 'Ehem. Masterstudent',
				description: 'In seiner Masterarbeit erforschte Nicco, wie externe zur HPI Schul-Cloud beitragen können, also sowohl technisch Beiträge zu erleichtern als auch sozial den Weg zu ebnen. In seiner Freizeit umgibt er sich gern mit Menschen, die ihr Umfeld aktiv gestalten, so auch ihr digitales. Deswegen organisiert er auch das <a href="https://hpi.de/veranstaltungen/schuelerveranstaltungen/2014/coder-dojo-offene-programmier-samstage-am-hpi.html" target="_blank">CoderDojo am HPI</a> mit, bei #tec, dem <a href="https://opentechsummit.net/" target="_blank">OpenTechSummit</a>, bei <a href="https://blog.freifunk-potsdam.de/" target="_blank">Freifunk</a> und <a href="https://gci17.fossasia.org/" target="_blank">FOSSASIA</a>.',
				pictureUrl: '/images/team/Nicco_Kunzmann.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Lars',
				lastName: 'Lange',
				position: 'Ehem. Bachelorstudent',
				description: 'Lars hat IT-Systems-Engineering am Hasso-Plattner-Institut im Bachelor studiert und hat vor Beendigung seines Studiums einen Richtungswechsel in die allgemeine Informatik an der Freien Universität Berlin gemacht. Im Projekt war er unter anderem mitverantwortlich für das Frontend, Backend, die Android App und alles rund um die Server Architektur. In seiner Freizeit geht er gerne schwimmen oder fährt gelegentlich Rennrad.',
				pictureUrl: '/images/team/Lars_Lange.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Elias',
				lastName: 'Maass',
				position: 'Ehem. Bachelorstudent',
				description: 'Elias studierte am Hasso-Plattner-Institut IT-Systems Engineering im Bachelor und war Teil des Bachelorprojektes 2018/19 bei der HPI Schul-Cloud. In seiner Freizeit hört er Musik verschiedenster Künstler und macht regelmäßig Sport.',
				pictureUrl: '/images/team/Elias_Maass.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Marco',
				lastName: 'Schaarschmidt',
				position: 'Ehem. Bachelorstudent',
				description: 'Marco studierte am Hasso-Plattner-Institut IT-Systems Engineering im Bachelor und war Teil des Bachelorprojektes 2018/19 bei der HPI Schul-Cloud. Neben dem Studium geht er schwimmen und verbringt er seine Freizeit sehr gerne damit zu reisen und neue, interessante Orte kennenzulernen.',
				pictureUrl: '/images/team/Marco_Schaarschmidt.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Sebastian',
				lastName: 'Serth',
				position: 'Ehem. Masterstudent',
				description: 'Sebastian hat seine Masterarbeit im Kontext der HPI Schul-Cloud geschrieben. Als Grundlage dazu dienten ihm Erkenntnisse von openHPI, der Online-Lernplattform des HPI, in dessen Rahmen er bereits seine Bachelorarbeit angefertigt hat. In seiner Masterarbeit untersuchte er, wie Lehrer individuelle Arbeitsblätter mit interaktiven Programmieraufgaben erstellen und im Unterricht einsetzen können: die Schüler arbeiten dazu wie bei Online-Kursen in der webbasierten Programmierumgebung CodeOcean, in der sie ihre Programme entwickeln, ausführen und mit Hilfe automatisierter Tests ihrer Lehrer sogar eigenständig überprüfen können. Die Lehrer erhalten einen besseren Überblick über den Lernfortschritt der Klasse und können so bei auftretenden Problemen zeitnah und zielorientiert Unterstützung leisten. In seiner Freizeit springt Sebastian leidenschaftlich gern auf dem Großtrampolin, reist mit Vergnügen durch fremde Länder und hält dabei seine Eindrücke fotografisch fest.',
				pictureUrl: '/images/team/Sebastian_Serth.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Johannes',
				lastName: 'Unruh',
				position: 'Ehem. Bachelorstudent',
				description: 'Johannes studierte am Hasso-Plattner-Institut IT-Systems Engineering im Bachelor und war Teil des Bachelorprojektes 2018/19 bei der HPI Schul-Cloud. Zuvor hat er einen Master in Wirtschaftsingenieurwesen an der TU Berlin erworben. Neben der Uni beschäftigt er sich mit Themen der Künstlichen Intelligenz und des Web Development.',
				pictureUrl: '/images/team/Johannes_Unruh.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
			{
				title: '',
				firstName: 'Florian',
				lastName: 'Wirtz',
				position: 'Ehem. Bachelorstudent',
				description: 'Florian war studentische Hilfskraft im Team HPI Schul-Cloud sowie Mitglied des Bachelorprojekts 2017/18. Seine Arbeit dort war vor allem durch Forschung im Bereich der Content-Erstellung und -Integration charakterisiert. In seiner Freizeit engagiert er sich ehrenamtlich in der Ausrichtung von Hackathons und findet Ausgleich im Radfahren, Sport und Reisen.',
				pictureUrl: '/images/team/Florian_Wiertz.jpg',
				priority: 0,
				social: {
					facebook: '',
					twitter: '',
					linkedin: '',
				},
				longDesc: false,
			},
		],
	},
].filter((t) => t.team.length).map((t, i) => {
	t.style = sectionTypes[i % sectionTypes.length];
	return t;
});
