const {
	FEATURE_ALERTS_ON_HOMEPAGE_ENABLED,
	FEATURE_BUTTONS_ON_LOGINPAGE_ENABLED,
} = process.env;

const exp = {
	FEATURE_ALERTS_ON_HOMEPAGE_ENABLED,
	FEATURE_BUTTONS_ON_LOGINPAGE_ENABLED,
};

module.exports = exp;
