const {
	NODE_ENV = 'development',
	JWT_SHOW_TIMEOUT_WARNING_SECONDS = 3600, // 60 min
	JWT_TIMEOUT_SECONDS,
	MAXIMUM_ALLOWABLE_TOTAL_ATTACHMENTS_SIZE_BYTE = (5 * 1024 * 1024), // 5MB
	MINIMAL_PASSWORD_LENGTH = 12,
	FEATURE_TEAMS_ENABLED = 'true',
	FEATURE_EXTENSIONS_ENABLED,
	SW_ENABLED,
	HOST = 'http://localhost',
	PORT = '3100',
	FEATURE_ENTERTHECLOUD,
	FEATURE_JWT_EXTENDED_TIMEOUT_ENABLED,
	FEATURE_CONTACT_FORM_ATTACHMENTS_ENABLED,
	FEATURE_MINT_PAGES_ENABLED,
	ALERT_STATUS_URL = 'https://status.dbildungscloud.de',
	FEATURE_ALERTS_ON_HOMEPAGE_ENABLED,
	FEATURE_BUTTONS_ON_LOGINPAGE_ENABLED,
} = process.env;

const exp = {
	NODE_ENV,
	JWT_SHOW_TIMEOUT_WARNING_SECONDS,
	JWT_TIMEOUT_SECONDS,
	MAXIMUM_ALLOWABLE_TOTAL_ATTACHMENTS_SIZE_BYTE,
	MINIMAL_PASSWORD_LENGTH,
	FEATURE_TEAMS_ENABLED,
	FEATURE_EXTENSIONS_ENABLED,
	SW_ENABLED,
	HOST,
	PORT,
	FEATURE_ENTERTHECLOUD,
	FEATURE_JWT_EXTENDED_TIMEOUT_ENABLED,
	FEATURE_CONTACT_FORM_ATTACHMENTS_ENABLED,
	FEATURE_MINT_PAGES_ENABLED,
	ALERT_STATUS_URL,
	FEATURE_ALERTS_ON_HOMEPAGE_ENABLED,
	FEATURE_BUTTONS_ON_LOGINPAGE_ENABLED,
};

module.exports = exp;
