---
name: Build and push Docker Image

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  build_instances:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tennens: [ brb, n21 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: |
         declare -x SC_THEME=${{ matrix.tennens }}
         TZ=Europe/Berlin
         gulp clear-cache
         gulp
      - run: tar -cf ${{ matrix.tennens }}.tar bin build
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.tennens }}
          path: ${{github.workspace }}/${{ matrix.tennens }}.tar