---
name: e2e management

on:
  push:
    branches-ignore:
      - dependabot/**

jobs:
  wait_for_image:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 6 min
        run: sleep 360s
        shell: bash
  tag-managment:
    needs: wait_for_image
    uses: hpi-schul-cloud/end-to-end-tests/.github/workflows/e2e.yml@main
    with:
      ref: ${{ github.ref }}
      e2e_tag: management

