---
name: Build and push Docker Image on Tag

on:
  push:
    tags:
      - '[0-9]*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    strategy:
      matrix:
        tenants: [default, brb, n21, thr ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Docker meta Service Name for docker hub
        id: docker_meta_img_hub
        uses: docker/metadata-action@v4
        with:
          images: schulcloud/schulcloud-client-${{ matrix.tenants }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push ${{ github.repository }}
        uses: docker/build-push-action@v4
        with:
          build-args: |
            SC_THEME_BUILD=${{ matrix.tenants }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta_img_hub.outputs.tags }}
          labels: ${{ steps.docker_meta_img_hub.outputs.labels }}


  create-release:
      needs:
          - build_and_push
      runs-on: ubuntu-latest
      permissions:
          actions: read
          contents: write
      steps:
          - name: create sbom
            uses: aquasecurity/trivy-action@e5f43133f6e8736992c9f3c1b3296e24b37e17f2
            with:
                scan-type: 'image'
                format: 'cyclonedx'
                image-ref: 'docker.io/schulcloud/schulcloud-client-default:${{ github.ref_name }}'
                output: 'dependency-results.sbom.json'
          - name: create release
            uses: softprops/action-gh-release@v1
            with:
                files: dependency-results.sbom.json
